units:
  Wolf:
    unitProperties:
      weight: 50
      moveSpeed: 30
      weightEatToFill: 8
    type: CARNIVOROUS
    availableActions:
      - MOVE
      - EAT
      - REPRODUCTION
    emoji: "üê∫"
    maxByLocation: 30
    eatChance:
      Snake: 0
      Fox: 0
      Bear: 0
      Eagle: 0
      Horse: 10
      Deer: 10
      Rabbit: 60
      Mouse: 80
      Goat: 60
      Sheep: 70
      Boar: 15
      Buffalo: 10
      Duck: 40
      Larva: 0
      Bush: 0
  Snake:
    unitProperties:
      weight: 15
      moveSpeed: 1
      weightEatToFill: 3
    type: CARNIVOROUS
    availableActions:
      - MOVE
      - EAT
      - REPRODUCTION
    emoji: "üêç"
    maxByLocation: 30
    eatChance:
      Wolf: 0
      Fox: 15
      Bear: 0
      Eagle: 0
      Horse: 0
      Deer: 0
      Rabbit: 20
      Mouse: 40
      Goat: 0
      Sheep: 0
      Boar: 0
      Buffalo: 0
      Duck: 10
      Larva: 0
      Bush: 0
  Fox:
    unitProperties:
      weight: 8
      moveSpeed: 2
      weightEatToFill: 2
    type: CARNIVOROUS
    availableActions:
      - MOVE
      - EAT
      - REPRODUCTION
    emoji: "ü¶ä"
    maxByLocation: 30
    eatChance:
      Wolf: 0
      Snake: 0
      Bear: 0
      Eagle: 0
      Horse: 0
      Deer: 0
      Rabbit: 70
      Mouse: 90
      Goat: 0
      Sheep: 0
      Boar: 0
      Buffalo: 0
      Duck: 60
      Larva: 40
      Bush: 0
  Bear:
    unitProperties:
      weight: 500
      moveSpeed: 2
      weightEatToFill: 80
    type: CARNIVOROUS
    availableActions:
      - MOVE
      - EAT
      - REPRODUCTION
    emoji: "üêª"
    maxByLocation: 5
    eatChance:
      Wolf: 0
      Snake: 0
      Fox: 80
      Eagle: 0
      Horse: 40
      Deer: 80
      Rabbit: 80
      Mouse: 90
      Goat: 70
      Sheep: 70
      Boar: 50
      Buffalo: 20
      Duck: 10
      Larva: 0
      Bush: 0
  Eagle:
    unitProperties:
      weight: 6
      moveSpeed: 3
      weightEatToFill: 1
    type: CARNIVOROUS
    availableActions:
      - MOVE
      - EAT
      - REPRODUCTION
    emoji: "ü¶Ö"
    maxByLocation: 20
    eatChance:
      Wolf: 0
      Snake: 0
      Fox: 10
      Bear: 0
      Horse: 0
      Deer: 0
      Rabbit: 90
      Mouse: 90
      Goat: 0
      Sheep: 0
      Boar: 0
      Buffalo: 0
      Duck: 80
      Larva: 0
      Bush: 0
  Horse:
    unitProperties:
      weight: 400
      moveSpeed: 4
      weightEatToFill: 60
    type: HERBIVOROUS
    availableActions:
      - MOVE
      - EAT
      - REPRODUCTION
    emoji: "üê¥"
    maxByLocation: 20
    eatChance:
      Wolf: 0
      Snake: 0
      Fox: 0
      Bear: 0
      Eagle: 0
      Deer: 0
      Rabbit: 0
      Mouse: 0
      Goat: 0
      Sheep: 0
      Boar: 0
      Buffalo: 0
      Duck: 0
      Larva: 0
      Bush: 100
  Deer:
    unitProperties:
      weight: 300
      moveSpeed: 4
      weightEatToFill: 50
    type: HERBIVOROUS
    availableActions:
      - MOVE
      - EAT
      - REPRODUCTION
    emoji: "ü¶å"
    maxByLocation: 20
    eatChance:
      Wolf: 0
      Snake: 0
      Fox: 0
      Bear: 0
      Eagle: 0
      Horse: 0
      Rabbit: 0
      Mouse: 0
      Goat: 0
      Sheep: 0
      Boar: 0
      Buffalo: 0
      Duck: 0
      Larva: 0
      Bush: 100
  Rabbit:
    unitProperties:
      weight: 2
      moveSpeed: 2
      weightEatToFill: 0.45
    type: HERBIVOROUS
    availableActions:
      - MOVE
      - EAT
      - REPRODUCTION
    emoji: "üêá"
    maxByLocation: 150
    eatChance:
      Wolf: 0
      Snake: 0
      Fox: 0
      Bear: 0
      Eagle: 0
      Horse: 0
      Deer: 0
      Mouse: 0
      Goat: 0
      Sheep: 0
      Boar: 0
      Buffalo: 0
      Duck: 0
      Larva: 0
      Bush: 100
  Mouse:
    unitProperties:
      weight: 2
      moveSpeed: 2
      weightEatToFill: 0.45
    type: CARNIVOROUS
    availableActions:
      - MOVE
      - EAT
      - REPRODUCTION
    emoji: "üêÅ"
    maxByLocation: 150
    eatChance:
      Wolf: 0
      Snake: 0
      Fox: 0
      Bear: 0
      Eagle: 0
      Horse: 0
      Deer: 0
      Rabbit: 0
      Goat: 0
      Sheep: 0
      Boar: 0
      Buffalo: 0
      Duck: 0
      Larva: 90
      Bush: 100
  Goat:
    unitProperties:
      weight: 60
      moveSpeed: 3
      weightEatToFill: 10
    type: HERBIVOROUS
    availableActions:
      - MOVE
      - EAT
      - REPRODUCTION
    emoji: "üêê"
    maxByLocation: 140
    eatChance:
      Wolf: 0
      Snake: 0
      Fox: 0
      Bear: 0
      Eagle: 0
      Horse: 0
      Deer: 0
      Rabbit: 0
      Mouse: 0
      Sheep: 0
      Boar: 0
      Buffalo: 0
      Duck: 0
      Larva: 0
      Bush: 100
  Sheep:
    unitProperties:
      weight: 70
      moveSpeed: 3
      weightEatToFill: 15
    type: HERBIVOROUS
    availableActions:
      - MOVE
      - EAT
      - REPRODUCTION
    emoji: "üêë"
    maxByLocation: 140
    eatChance:
      Wolf: 0
      Snake: 0
      Fox: 0
      Bear: 0
      Eagle: 0
      Horse: 0
      Deer: 0
      Rabbit: 0
      Mouse: 0
      Goat: 0
      Boar: 0
      Buffalo: 0
      Duck: 0
      Larva: 0
      Bush: 100
  Boar:
    unitProperties:
      weight: 400
      moveSpeed: 2
      weightEatToFill: 50
    type: CARNIVOROUS
    availableActions:
      - MOVE
      - EAT
      - REPRODUCTION
    emoji: "üêó"
    maxByLocation: 50
    eatChance:
      Wolf: 0
      Snake: 0
      Fox: 0
      Bear: 0
      Eagle: 0
      Horse: 0
      Deer: 0
      Rabbit: 0
      Mouse: 0
      Goat: 0
      Sheep: 0
      Buffalo: 0
      Duck: 0
      Larva: 90
      Bush: 100
  Buffalo:
    unitProperties:
      weight: 700
      moveSpeed: 3
      weightEatToFill: 100
    type: HERBIVOROUS
    availableActions:
      - MOVE
      - EAT
      - REPRODUCTION
    emoji: "üêÉ"
    maxByLocation: 10
    eatChance:
      Wolf: 0
      Snake: 0
      Fox: 0
      Bear: 0
      Eagle: 0
      Horse: 0
      Deer: 0
      Rabbit: 0
      Mouse: 0
      Goat: 0
      Sheep: 0
      Boar: 0
      Duck: 0
      Larva: 0
      Bush: 100
  Duck:
    unitProperties:
      weight: 1
      moveSpeed: 4
      weightEatToFill: 0.15
    type: CARNIVOROUS
    availableActions:
      - MOVE
      - EAT
      - REPRODUCTION
    emoji: "ü¶Ü"
    maxByLocation: 200
    eatChance:
      Wolf: 0
      Snake: 0
      Fox: 0
      Bear: 0
      Eagle: 0
      Horse: 0
      Deer: 0
      Rabbit: 0
      Mouse: 0
      Goat: 0
      Sheep: 0
      Boar: 0
      Buffalo: 0
      Larva: 90
      Bush: 100
  Larva:
    unitProperties:
      weight: 0.01
      moveSpeed: 0
      weightEatToFill: 1
    type: HERBIVOROUS
    availableActions:
      - MOVE
      - EAT
      - REPRODUCTION
    emoji: "üêõ"
    maxByLocation: 1000
    eatChance:
      Wolf: 0
      Snake: 0
      Fox: 0
      Bear: 0
      Eagle: 0
      Horse: 0
      Deer: 0
      Rabbit: 0
      Mouse: 0
      Goat: 0
      Sheep: 0
      Boar: 0
      Buffalo: 0
      Duck: 0
      Bush: 100
  Bush:
    unitProperties:
      weight: 1
      moveSpeed: 0
      weightEatToFill: 0
    type: PLANT
    availableActions: []
    emoji: "üåµ"
    maxByLocation: 200
    eatChance:
      Wolf: 0
      Snake: 0
      Fox: 0
      Bear: 0
      Eagle: 0
      Horse: 0
      Deer: 0
      Rabbit: 0
      Mouse: 0
      Goat: 0
      Sheep: 0
      Boar: 0
      Buffalo: 0
      Duck: 0
      Larva: 0